### ISSUE TITLE
please add High DPI support

### ISSUE THREAD

**Issue by bestw** [wxMEdit/wxMEdit#173] opened 2018-04-16 08:42 UTC
please add High DPI support, it's a bit fuzzy in high solution.

**Comment by Neonking** [comment] 2018-04-16 10:34
hi @bestw ,
Thanks for the suggestion. There is on-going work about icons to have them more correct in higher resolutions. Excepted icons, did you have something in mind regarding the High DPI support?
Regards,
Jerome

**Comment by bestw** [comment] 2018-04-16 13:59
Thanks for reply.
I mean in Windows 10, when using in high DPI for example 200% display, font is fuzzy, unable to be seen clearly. Can you support this feature, after all high DPI displays becoming more and more common.

**Comment by Neonking** [comment] 2018-04-16 15:08
Ok, seems anti-aliasing goes wrong , maybe also an issue from the default font . There are some full Unicode font around and as well as encoding/character support is a big feature in wxMEdit, i think we should rely on one of them as default font, maybe include some as internal resource. Some examples [Here](http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=FontDownloads) and [Here](http://www.wazu.jp/).
But Back to the high DPI issue , @bestw  could you provide a screenshot of the rendered stuff in your large resolution as example ? 
Regards,
Jerome

**Comment by bestw** [comment] 2018-04-17 01:54
![screensnap](https://user-images.githubusercontent.com/12840229/38844197-f96c4658-4224-11e8-8dfa-614687283ab0.png)
Is that OK?

**Comment by Neonking** [comment] 2018-04-17 02:01
Perfect , Thank you for the feedback @bestw we will dig on this . Hopefully seems i was right ,sounds a combination of an aliasing issue with the default font . 
Hope i don't ask you too much if you mind testing with one or 2 other display fonts  (view>font name>...) and report us if the problem still occurs (screenshots welcome) ? Thank you in advance !
Regards,
Jerome

**Comment by bestw** [comment] 2018-04-17 02:43
No problem.
Consolas:
![consolas](https://user-images.githubusercontent.com/12840229/38845637-0322400c-422b-11e8-9040-888a131b66fe.png)
DejaVu Sans Mono:
![dejavu sans mono](https://user-images.githubusercontent.com/12840229/38845645-0cda5184-422b-11e8-91fd-212758808c34.png)
Times New Roman:
![times new roman](https://user-images.githubusercontent.com/12840229/38845744-7a174ea0-422b-11e8-8927-28df701536c3.png)
The default font is Courier New.

**Comment by Neonking** [comment] 2018-04-18 09:31
Thank you very much @bestw . As far as i see , the problem mainly occurs with the Default Courrier New font while with other fonts it looks like better . Can you confirm me that please ?
Regards,
Jerome

**Comment by hltj** [comment] 2018-04-19 02:01
@Neonking @bestw  this may be wxWidgets problem.

The first change of unstable release of 3.1.0 is just "Better support for high DPI displays, especially under Windows." : http://wxwidgets.org/news/2016/02/wxwidgets-3.1.0-released/

Therefore, maybe we can fix this issue after the next stable wxWidgets release (3.2) which is expected to be released before the end of the year.

**Comment by gli-spirent** [comment] 2019-04-09 07:15
This is not a bug or issue of wxWidgets but wxMEdit's. You have to support HDPI awareness while compiling with VS. You may refer to https://github.com/LiMinggang/madedit-mod

**Comment by hltj** [comment] 2019-05-10 03:28
> This is not a bug or issue of wxWidgets but wxMEdit's. You have to support HDPI awareness while compiling with VS. 

Thanks. I will enable DPI awareness when package Win32/Win64 binaries for wxMEdit 3.2.

**Comment by hltj** [comment] 2019-05-10 03:40
> This is not a bug or issue of wxWidgets but wxMEdit's. You have to support HDPI awareness while compiling with VS. You may refer to https://github.com/LiMinggang/madedit-mod

Thanks. But it may be a mistake.
I've checked the project properties and found that "per Monitor High DPI Aware" was already set.

**Comment by hltj** [comment] 2019-05-10 03:42
> This is not a bug or issue of wxWidgets but wxMEdit's. You have to support HDPI awareness while compiling with VS.

Thanks. I will enable DPI awareness when packaging Win32/Win64 binaries for wxMEdit 3.2.

**Comment by hltj** [comment] 2023-05-21 16:33
3.2RC is released. Already enable High DPI awareness for Win32/Win64.
https://wxmedit.github.io/zh_CN/downloads.html#prerelease
http://downloads.sourceforge.net/project/wxmedit/prerelease/3.1.0.90/wxMEdit-3.1.0.90-win64-bin.7z for x64 Windows 7 or later
http://downloads.sourceforge.net/project/wxmedit/prerelease/3.1.0.90/wxMEdit-3.1.0.90-win32-bin.7z for x86 Windows 7 or later
http://downloads.sourceforge.net/project/wxmedit/prerelease/3.1.0.90/wxMEdit-3.1.0.90-win32-bin-xp.7z for Windows Xp/Vistar

This release is actually stable enough. While waiting for localization and packaging for each system, the formal 3.2 is expected to be released in two weeks.

**Comment by hltj** [comment] 2023-07-11 05:09
3.2 is released. Already enabled High DPI awareness for Win32/Win64.
https://wxmedit.github.io/downloads.html

| Operating System | Architecture | Package |
| ---------------- | ------------ | ------- |
| Windows 7 or later / Wine | amd64 | [wxMEdit-3.2-win64-bin.7z](http://downloads.sourceforge.net/project/wxmedit/3.2/wxMEdit-3.2-win64-bin.7z) 12.8 MiB<br>[wxMEdit-3.2-win64-bin.zip](http://downloads.sourceforge.net/project/wxmedit/3.2/wxMEdit-3.2-win64-bin.zip) 20.7 MiB |
| Windows XP or later / Wine | i386 | [wxMEdit-3.2-win32-bin.7z](https://downloads.sourceforge.net/project/wxmedit/3.2/wxMEdit-3.2-win32-bin.7z) 11.6 MiB<br>[wxMEdit-3.2-win32-bin.zip](https://downloads.sourceforge.net/project/wxmedit/3.2/wxMEdit-3.2-win32-bin.zip) 18.7 MiB |
| ReactOS | i386/amd64 | [wxMEdit-3.2-win32-bin-ros.7z](http://downloads.sourceforge.net/project/wxmedit/3.2/wxMEdit-3.2-win32-bin-ros.7z) 9.64 MiB<br>[wxMEdit-3.2-win32-bin-ros.zip](http://downloads.sourceforge.net/project/wxmedit/3.2/wxMEdit-3.2-win32-bin-ros.zip) 15.7 MiB |

**Closed by hltj** 2023-07-11 05:09 UTC
